[font]
normal = { family = "Triplicate A Code" }
size = 16.0

[colors]
cursor = { cursor = "#20bbfc", text = "#000000" }

[cursor]
style = "Beam"
thickness = 0.25

[bell]
# command = { program = "osascript", args = ["-e", "beep"] }
