theme = "littlecomputerpeople"

[editor]
color-modes = true
gutters = ["diff", "spacer", "diagnostics", "line-numbers", "spacer"] 

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal.space]
z = ":toggle gutters.line-numbers.min-width 3 31"
