theme = "littlecomputerpeople"

[editor]
color-modes = true
gutters = ["diff", "spacer", "diagnostics", "line-numbers", "spacer"]

[editor.smart-tab]
enable = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal.space]
z = ":toggle gutters.line-numbers.min-width 3 15" 

[keys.normal.minus] 
c = "collapse_selection" 
s = "split_selection_on_newline" 
"%" = "split_selection" 
f = "flip_selections" 
k = "keep_primary_selection" 
r = "remove_primary_selection" 
n = "rotate_selections_forward" 
p = "rotate_selections_backward" 
