theme = "littlecomputerpeople"

[editor]
color-modes = true
gutters = ["diff", "spacer", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true
max-wrap = 25
wrap-at-text-width = true
wrap-indicator = ""

[editor.smart-tab]
enable = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal.space]
z = ":toggle gutters.line-numbers.min-width 3 31" 

[keys.normal.g]
"ret" = "goto_line_end_newline"
