theme = "littlecomputerpeople"

[editor]
color-modes = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal.space]
Z = ":set gutters.line-numbers.min-width 3"
z = ":set gutters.line-numbers.min-width 31"